version: "3.8"
services:
    # Mysql database container
    db:
        image: mysql
        container_name: jor_db_symfony
        restart: always
        volumes:
            - db-data:/var/lib/mysql
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        networks:
            - forum

    # phpmyadmin container
    phpmyadmin:
        image: phpmyadmin
        container_name: jor_phpmyadmin
        restart: always
        depends_on:
            - db
        ports:
            - 8080:80
        environment:
            PMA_HOST: db
        networks:
            - forum

    # Symfony apache project container
    www:
        build: docker/php
        container_name: jor_symfony
        ports:
          - "8742:80"
        volumes:
            - ./docker/php/vhosts:/etc/apache2/sites-enabled
            - ./:/var/www
        restart: always
        networks:
            - forum

       # React front-end container
    react-app:
        build:
          context: .
          dockerfile: docker/frontend/Dockerfile
        container_name: jor_react_frontend
        environment:
          - NODE_ENV=development
          - WATCHPACK_POLLING=true
        volumes:
          - ./frontend:/app
        ports:
          - "3000:3000"
        networks:
          - forum

networks:
    forum:

volumes:
    db-data: